const events=[
 {id:1,title:'Bangkok Youth League',date:'18 ส.ค. 2569',place:'สนามฟุตบอล KMITL',photos:'1,248 ภาพ',type:'football',tag:'ใหม่',img:'https://images.unsplash.com/photo-1526232761682-d26e03ac148e?auto=format&fit=crop&w=900&q=80'},
 {id:2,title:'Junior Champions Cup',date:'12 ส.ค. 2569',place:'Alpine Football Camp',photos:'864 ภาพ',type:'football',tag:'ยอดนิยม',img:'https://images.unsplash.com/photo-1517466787929-bc90951d0974?auto=format&fit=crop&w=900&q=80'},
 {id:3,title:'City Night Run 2026',date:'9 ส.ค. 2569',place:'สวนหลวง ร.9',photos:'2,105 ภาพ',type:'running',tag:'ใหม่',img:'https://images.unsplash.com/photo-1552674605-db6ffd4facb5?auto=format&fit=crop&w=900&q=80'},
 {id:4,title:'Academy Friendly Match',date:'3 ส.ค. 2569',place:'BCoE Academy',photos:'592 ภาพ',type:'football',tag:'',img:'https://images.unsplash.com/photo-1600679472829-3044539ce8ed?auto=format&fit=crop&w=900&q=80'},
 {id:5,title:'Swimming Talent Series',date:'27 ก.ค. 2569',place:'Aquatic Center',photos:'740 ภาพ',type:'other',tag:'',img:'https://images.unsplash.com/photo-1530137073520-4ea6e2f10a48?auto=format&fit=crop&w=900&q=80'},
 {id:6,title:'Bangkok Basketball Open',date:'20 ก.ค. 2569',place:'Sports Complex',photos:'921 ภาพ',type:'other',tag:'',img:'https://images.unsplash.com/photo-1546519638-68e109498ffc?auto=format&fit=crop&w=900&q=80'}
];
const jobs=events.slice(0,4);let filter='all';
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
function card(e){return `<article class="event-card" data-event="${e.id}"><div class="event-cover" style="background-image:url('${e.img}')">${e.tag?`<span>${e.tag}</span>`:''}</div><div class="event-info"><h3>${e.title}</h3><p>${e.date} · ${e.place}</p><div class="event-meta"><span>${e.photos}</span><b>เปิดอัลบั้ม →</b></div></div></article>`}
function render(){ $('#latestGrid').innerHTML=events.slice(0,3).map(card).join(''); const q=($('#eventSearch')?.value||'').toLowerCase(); $('#eventGrid').innerHTML=events.filter(e=>(filter==='all'||e.type===filter)&&(`${e.title} ${e.place}`.toLowerCase().includes(q))).map(card).join('')||'<p>ไม่พบอัลบั้มที่ค้นหา</p>'; bindCards() }
function bindCards(){$$('[data-event]').forEach(el=>el.onclick=()=>openAlbum(events.find(e=>e.id==el.dataset.event)))}
function go(id){$$('.view').forEach(v=>v.classList.remove('active-view'));$('#'+id).classList.add('active-view');$$('.nav-link').forEach(n=>n.classList.toggle('active',n.dataset.view===id));scrollTo({top:0,behavior:'smooth'})}
function modal(html){$('#modalBody').innerHTML=html;$('#modal').classList.add('open');$('#modal').setAttribute('aria-hidden','false')}
function closeModal(){$('#modal').classList.remove('open')}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2500)}
function openAlbum(e){modal(`<span class="eyebrow"><i></i> EVENT GALLERY</span><h2>${e.title}</h2><p>${e.date} · ${e.place}</p><div class="drop-zone"><b>${e.photos}</b><p>ค้นหาภาพของคุณในอัลบั้มนี้</p></div><input id="shirtNo" placeholder="หมายเลขเสื้อ (ไม่บังคับ)"><button class="primary" style="width:100%" id="albumFace">⌾ ค้นหาด้วยใบหน้า</button>`);$('#albumFace').onclick=faceModal}
function faceModal(){modal(`<span class="eyebrow"><i></i> FACE SEARCH</span><h2>ค้นหาภาพด้วยใบหน้า</h2><p>เลือกรูปหน้าตรงที่เห็นใบหน้าชัด ระบบจะไม่นำรูปไปเผยแพร่หรือเก็บไว้นานเกินการค้นหา</p><div class="drop-zone" id="faceDrop"><span class="upload-icon">⌾</span><b>แตะเพื่อเลือกรูปใบหน้า</b><p>รองรับ JPG, PNG</p></div><input type="file" id="faceFile" accept="image/*" hidden><button class="primary" style="width:100%" id="startFace">เริ่มค้นหา</button>`);$('#faceDrop').onclick=()=>$('#faceFile').click();$('#faceFile').onchange=()=>toast('เลือกรูปแล้ว พร้อมเริ่มค้นหา');$('#startFace').onclick=()=>{closeModal();toast('กำลังเตรียมระบบค้นหาใบหน้า — เวอร์ชันนี้เป็นหน้าทดลอง')}}
$$('.nav-link').forEach(n=>n.onclick=()=>go(n.dataset.view));$$('[data-go]').forEach(n=>n.onclick=()=>go(n.dataset.go));$('#faceSearch').onclick=faceModal;$('#searchBtn').onclick=()=>go('events');$('#modalClose').onclick=closeModal;$('#modal').onclick=e=>{if(e.target.id==='modal')closeModal()};
$('#loginBtn').onclick=()=>modal(`<span class="eyebrow"><i></i> SECURE ACCESS</span><h2>เข้าสู่ระบบ</h2><input placeholder="อีเมล"><input type="password" placeholder="รหัสผ่าน"><select><option>ผู้ปกครอง / บุคคลทั่วไป</option><option>ช่างภาพ</option><option>ผู้ดูแลระบบ</option></select><button class="primary" style="width:100%" id="doLogin">เข้าสู่ระบบ</button><p style="text-align:center">ยังไม่มีบัญชี? <u id="register" style="cursor:pointer">สมัครเป็นช่างภาพ</u></p>`);document.addEventListener('click',e=>{if(e.target.id==='doLogin'){closeModal();toast('เข้าสู่โหมดทดลองเรียบร้อย')}if(e.target.id==='register'){modal(`<h2>สมัครเป็นช่างภาพ</h2><input placeholder="ชื่อ-นามสกุล"><input placeholder="อีเมล"><input placeholder="เบอร์โทรศัพท์"><input placeholder="ลิงก์ผลงาน"><button class="primary" style="width:100%" id="submitRegister">ส่งคำขอสมัคร</button>`)}if(e.target.id==='submitRegister'){closeModal();toast('ส่งคำขอแล้ว ผู้ดูแลจะตรวจสอบก่อนเปิดใช้งาน')}});
$('#newAlbum').onclick=()=>modal(`<h2>สร้างอัลบั้มใหม่</h2><input placeholder="ชื่อการแข่งขัน"><input type="date"><input placeholder="สถานที่"><select><option>ฟุตบอล</option><option>วิ่ง</option><option>กีฬาอื่น ๆ</option></select><button class="primary" style="width:100%" id="createAlbum">สร้างและไปอัปโหลดภาพ</button>`);document.addEventListener('click',e=>{if(e.target.id==='createAlbum'){closeModal();toast('สร้างอัลบั้มฉบับร่างแล้ว')}});$('#uploadBtn').onclick=()=>$('#fileInput').click();$('#fileInput').onchange=e=>toast(`เลือก ${e.target.files.length} ไฟล์ พร้อมอัปโหลด`);
$$('.filter').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;$$('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');render()});$('#eventSearch').oninput=render;
$('#jobList').innerHTML=jobs.map((j,i)=>`<div class="job"><div class="job-thumb" style="background-image:url('${j.img}')"></div><div><h4>${j.title}</h4><p>${j.date} · ${j.photos}</p></div><span class="status ${i<2?'live':''}">${i<2?'เผยแพร่แล้ว':'ฉบับร่าง'}</span></div>`).join('');render();
