const events=[
 {id:1,title:'Bangkok Youth League',date:'18 ส.ค. 2569',place:'สนามฟุตบอล KMITL',photos:'1,248 ภาพ',type:'football',tag:'ใหม่',img:'https://images.unsplash.com/photo-1526232761682-d26e03ac148e?auto=format&fit=crop&w=900&q=80'},
 {id:2,title:'Junior Champions Cup',date:'12 ส.ค. 2569',place:'Alpine Football Camp',photos:'864 ภาพ',type:'football',tag:'ยอดนิยม',img:'https://images.unsplash.com/photo-1517466787929-bc90951d0974?auto=format&fit=crop&w=900&q=80'},
 {id:3,title:'City Night Run 2026',date:'9 ส.ค. 2569',place:'สวนหลวง ร.9',photos:'2,105 ภาพ',type:'running',tag:'ใหม่',img:'https://images.unsplash.com/photo-1552674605-db6ffd4facb5?auto=format&fit=crop&w=900&q=80'},
 {id:4,title:'Academy Friendly Match',date:'3 ส.ค. 2569',place:'BCoE Academy',photos:'592 ภาพ',type:'football',tag:'',img:'https://images.unsplash.com/photo-1600679472829-3044539ce8ed?auto=format&fit=crop&w=900&q=80'},
 {id:5,title:'Swimming Talent Series',date:'27 ก.ค. 2569',place:'Aquatic Center',photos:'740 ภาพ',type:'other',tag:'',img:'https://images.unsplash.com/photo-1530137073520-4ea6e2f10a48?auto=format&fit=crop&w=900&q=80'},
 {id:6,title:'Bangkok Basketball Open',date:'20 ก.ค. 2569',place:'Sports Complex',photos:'921 ภาพ',type:'other',tag:'',img:'https://images.unsplash.com/photo-1546519638-68e109498ffc?auto=format&fit=crop&w=900&q=80'}
];
const jobs=events.slice(0,4);let filter='all';
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
function card(e){return `<article class="event-card" data-event="${e.id}"><div class="event-cover" style="background-image:url('${e.img}')">${e.tag?`<span>${e.tag}</span>`:''}</div><div class="event-info"><h3>${e.title}</h3><p>${e.date} · ${e.place}</p><div class="event-meta"><span>${e.photos}</span><b>เปิดอัลบั้ม →</b></div></div></article>`}
function render(){ $('#latestGrid').innerHTML=events.slice(0,3).map(card).join(''); const q=($('#eventSearch')?.value||'').toLowerCase(); $('#eventGrid').innerHTML=events.filter(e=>(filter==='all'||e.type===filter)&&(`${e.title} ${e.place}`.toLowerCase().includes(q))).map(card).join('')||'<p>ไม่พบอัลบั้มที่ค้นหา</p>'; bindCards() }
function bindCards(){$$('[data-event]').forEach(el=>el.onclick=()=>openAlbum(events.find(e=>e.id==el.dataset.event)))}
function go(id){$$('.view').forEach(v=>v.classList.remove('active-view'));$('#'+id).classList.add('active-view');$$('.nav-link').forEach(n=>n.classList.toggle('active',n.dataset.view===id));scrollTo({top:0,behavior:'smooth'})}
function modal(html){$('#modalBody').innerHTML=html;$('#modal').classList.add('open');$('#modal').setAttribute('aria-hidden','false')}
function closeModal(){$('#modal').classList.remove('open')}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2500)}
function openAlbum(e){modal(`<span class="eyebrow"><i></i> EVENT GALLERY</span><h2>${e.title}</h2><p>${e.date} · ${e.place}</p><div class="drop-zone"><b>${e.photos}</b><p>ค้นหาภาพของคุณในอัลบั้มนี้</p></div><input id="shirtNo" placeholder="หมายเลขเสื้อ (ไม่บังคับ)"><button class="primary" style="width:100%" id="albumFace">⌾ ค้นหาด้วยใบหน้า</button>`);$('#albumFace').onclick=faceModal}
function faceModal(){modal(`<span class="eyebrow"><i></i> FACE SEARCH</span><h2>ค้นหาภาพด้วยใบหน้า</h2><p>เลือกรูปหน้าตรงที่เห็นใบหน้าชัด ระบบจะไม่นำรูปไปเผยแพร่หรือเก็บไว้นานเกินการค้นหา</p><div class="drop-zone" id="faceDrop"><span class="upload-icon">⌾</span><b>แตะเพื่อเลือกรูปใบหน้า</b><p>รองรับ JPG, PNG</p></div><input type="file" id="faceFile" accept="image/*" hidden><button class="primary" style="width:100%" id="startFace">เริ่มค้นหา</button>`);$('#faceDrop').onclick=()=>$('#faceFile').click();$('#faceFile').onchange=()=>toast('เลือกรูปแล้ว พร้อมเริ่มค้นหา');$('#startFace').onclick=()=>{closeModal();toast('กำลังเตรียมระบบค้นหาใบหน้า — เวอร์ชันนี้เป็นหน้าทดลอง')}}
$$('.nav-link').forEach(n=>n.onclick=()=>go(n.dataset.view));$$('[data-go]').forEach(n=>n.onclick=()=>go(n.dataset.go));$('#faceSearch').onclick=faceModal;$('#searchBtn').onclick=()=>go('events');$('#modalClose').onclick=closeModal;$('#modal').onclick=e=>{if(e.target.id==='modal')closeModal()};
$('#loginBtn').onclick=()=>modal(`<span class="eyebrow"><i></i> SECURE ACCESS</span><h2>เข้าสู่ระบบ</h2><input placeholder="อีเมล"><input type="password" placeholder="รหัสผ่าน"><select><option>ผู้ปกครอง / บุคคลทั่วไป</option><option>ช่างภาพ</option><option>ผู้ดูแลระบบ</option></select><button class="primary" style="width:100%" id="doLogin">เข้าสู่ระบบ</button><p style="text-align:center">ยังไม่มีบัญชี? <u id="register" style="cursor:pointer">สมัครเป็นช่างภาพ</u></p>`);document.addEventListener('click',e=>{if(e.target.id==='doLogin'){closeModal();toast('เข้าสู่โหมดทดลองเรียบร้อย')}if(e.target.id==='register'){modal(`<h2>สมัครเป็นช่างภาพ</h2><input placeholder="ชื่อ-นามสกุล"><input placeholder="อีเมล"><input placeholder="เบอร์โทรศัพท์"><input placeholder="ลิงก์ผลงาน"><button class="primary" style="width:100%" id="submitRegister">ส่งคำขอสมัคร</button>`)}if(e.target.id==='submitRegister'){closeModal();toast('ส่งคำขอแล้ว ผู้ดูแลจะตรวจสอบก่อนเปิดใช้งาน')}});
$('#newAlbum').onclick=()=>modal(`<h2>สร้างอัลบั้มใหม่</h2><input placeholder="ชื่อการแข่งขัน"><input type="date"><input placeholder="สถานที่"><select><option>ฟุตบอล</option><option>วิ่ง</option><option>กีฬาอื่น ๆ</option></select><button class="primary" style="width:100%" id="createAlbum">สร้างและไปอัปโหลดภาพ</button>`);document.addEventListener('click',e=>{if(e.target.id==='createAlbum'){closeModal();toast('สร้างอัลบั้มฉบับร่างแล้ว')}});$('#uploadBtn').onclick=()=>$('#fileInput').click();$('#fileInput').onchange=e=>toast(`เลือก ${e.target.files.length} ไฟล์ พร้อมอัปโหลด`);
$$('.filter').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;$$('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');render()});$('#eventSearch').oninput=render;
$('#jobList').innerHTML=jobs.map((j,i)=>`<div class="job"><div class="job-thumb" style="background-image:url('${j.img}')"></div><div><h4>${j.title}</h4><p>${j.date} · ${j.photos}</p></div><span class="status ${i<2?'live':''}">${i<2?'เผยแพร่แล้ว':'ฉบับร่าง'}</span></div>`).join('');render();

// Complete photographer workflow: album details → upload → edit → review → publish
const editPhotos=[events[0].img,events[1].img,events[2].img,events[3].img,events[4].img,events[5].img];
let color={brightness:100,contrast:100,saturate:100,hue:0}, rotation=0;
function albumWizard(step=1){
 if(step===1){modal(`<div class="wizard-head"><span>ขั้นตอน 1/2</span><h2>รายละเอียดอัลบั้ม</h2><p>ข้อมูลนี้จะแสดงให้ผู้ปกครองค้นหาอัลบั้ม</p></div><input id="albumTitle" value="Bangkok Youth League"><input id="albumDate" type="date" value="2026-08-20"><input id="albumPlace" value="สนามฟุตบอล KMITL"><select id="albumSport"><option>ฟุตบอล</option><option>วิ่ง</option><option>ว่ายน้ำ</option><option>กีฬาอื่น ๆ</option></select><label class="switch-row">เปิดค้นหาด้วยใบหน้า <input type="checkbox" checked></label><label class="switch-row">เปิดค้นหาหมายเลขเสื้อ <input type="checkbox" checked></label><button class="primary full" id="wizardNext">ต่อไป: อัปโหลดภาพ →</button>`);$('#wizardNext').onclick=()=>{localStorage.setItem('pf_album',$('#albumTitle').value);albumWizard(2)}}
 else {modal(`<div class="wizard-head"><span>ขั้นตอน 2/2</span><h2>อัปโหลดภาพต้นฉบับ</h2><p>ระบบรองรับ JPG, PNG และ RAW พร้อมสร้างไฟล์ Preview อัตโนมัติ</p></div><div class="drop-zone" id="wizardDrop"><span class="upload-icon">↑</span><b>แตะเลือกภาพ หรือลากมาวาง</b><p id="uploadStatus">ยังไม่ได้เลือกไฟล์</p></div><input type="file" id="wizardFiles" multiple accept="image/*" hidden><label class="switch-row">สำรองไฟล์ต้นฉบับ <input type="checkbox" checked></label><button class="primary full" id="startEditing">อัปโหลดและไปแต่งสี →</button>`);$('#wizardDrop').onclick=()=>$('#wizardFiles').click();$('#wizardFiles').onchange=e=>$('#uploadStatus').textContent=`เลือกแล้ว ${e.target.files.length} ภาพ`;$('#startEditing').onclick=()=>{closeModal();$('#editAlbumName').textContent=localStorage.getItem('pf_album')||'อัลบั้มใหม่';go('editor');toast('อัปโหลดเสร็จแล้ว พร้อมแต่งสี')}}
}
$('#newAlbum').onclick=()=>albumWizard(1);
function drawStrip(){ $('#photoStrip').innerHTML=editPhotos.map((src,i)=>`<div class="strip-photo ${i===0?'active':''}" data-edit-photo="${i}" style="background-image:url('${src}')"><span>${i+1}</span></div>`).join('');$$('[data-edit-photo]').forEach(x=>x.onclick=()=>{$$('.strip-photo').forEach(a=>a.classList.remove('active'));x.classList.add('active');$('#editPhoto').src=editPhotos[+x.dataset.editPhoto]}) }
function applyColor(){ $('#editPhoto').style.filter=`brightness(${color.brightness}%) contrast(${color.contrast}%) saturate(${color.saturate}%) hue-rotate(${color.hue}deg)`;$('#editPhoto').style.transform=`rotate(${rotation}deg)` }
drawStrip();$$('[data-filter]').forEach(r=>r.oninput=()=>{const k=r.dataset.filter;color[k]=+r.value;$(`#${k}Out`).value=r.value;applyColor()});
$$('[data-preset]').forEach(b=>b.onclick=()=>{const presets={sport:[106,118,132,0],natural:[103,104,105,0],cinema:[92,115,82,-8],bw:[102,120,0,0]};[color.brightness,color.contrast,color.saturate,color.hue]=presets[b.dataset.preset];applyColor();toast(`ใช้พรีเซ็ต ${b.textContent} แล้ว`)});
$('#resetColor').onclick=()=>{color={brightness:100,contrast:100,saturate:100,hue:0};rotation=0;applyColor();toast('รีเซ็ตเป็นภาพต้นฉบับแล้ว')};
$$('[data-adjust]').forEach(b=>b.onclick=()=>{$$('[data-adjust]').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.adjust-section').forEach(x=>x.classList.add('hidden'));$(`#${b.dataset.adjust}Adjust`).classList.remove('hidden')});
$('#aiEnhance').onclick=()=>{const bar=$('#aiRunning');bar.classList.add('show');setTimeout(()=>{bar.classList.remove('show');color={brightness:107,contrast:116,saturate:124,hue:-2};applyColor();toast('AI ปรับสี คัดภาพ และจัดกลุ่มใบหน้าเสร็จแล้ว')},1200)};
$('#rotatePhoto').onclick=()=>{rotation+=90;applyColor()};$('#backStudio').onclick=()=>go('studio');$('#saveDraft').onclick=()=>{localStorage.setItem('pf_draft',JSON.stringify(color));toast('บันทึกฉบับร่างแล้ว')};$('#addMorePhotos').onclick=()=>$('#fileInput').click();
$('#publishAlbum').onclick=()=>modal(`<span class="eyebrow"><i></i> FINAL REVIEW</span><h2>พร้อมเผยแพร่อัลบั้ม</h2><p>AI ตรวจพบภาพเบลอ 2 ภาพและซ่อนให้แล้ว ภาพที่พร้อมเผยแพร่ 6 ภาพ</p><div class="drop-zone"><b>✓ ตรวจคุณภาพเสร็จแล้ว</b><p>ค้นหาใบหน้า · หมายเลขเสื้อ · ลายน้ำ · ดาวน์โหลด</p></div><label class="switch-row">แจ้งเตือนผู้ติดตาม <input type="checkbox" checked></label><button class="primary full" id="confirmPublish">ยืนยันเผยแพร่</button>`);
document.addEventListener('click',e=>{if(e.target.id==='confirmPublish'){closeModal();go('studio');toast('เผยแพร่อัลบั้มและแจ้งเตือนผู้ติดตามแล้ว')}});

// Admin control center
const applicants=[['กิตติ ภาพกีฬา','ฟุตบอล · Portfolio 24 งาน'],['พิชญา ชัตเตอร์','วิ่ง · Portfolio 18 งาน'],['ธนพล Sportsnap','ฟุตบอลเยาวชน · 31 งาน'],['นภัส Action Frame','กีฬาหลากหลาย · 16 งาน']];
$('#approvalList').innerHTML=applicants.map((a,i)=>`<div class="approval"><div class="avatar">${a[0][0]}</div><div><h4>${a[0]}</h4><p>${a[1]}</p></div><div class="row-actions"><button data-reject="${i}">ปฏิเสธ</button><button class="approve" data-approve="${i}">อนุมัติ</button></div></div>`).join('');
$('#reviewList').innerHTML=events.slice(0,3).map((a,i)=>`<div class="review-row"><div class="job-thumb" style="background-image:url('${a.img}')"></div><div><h4>${a.title}</h4><p>${a.photos} · ${i?'รอ AI':'รอตรวจคุณภาพ'}</p></div><button class="secondary" data-review="${i}">ตรวจ</button></div>`).join('');
document.addEventListener('click',e=>{if(e.target.dataset.approve!==undefined){e.target.closest('.approval').remove();toast('อนุมัติช่างภาพและส่งข้อมูลเข้าสู่ระบบแล้ว')}if(e.target.dataset.reject!==undefined){e.target.closest('.approval').remove();toast('ปฏิเสธคำขอแล้ว')}if(e.target.dataset.review!==undefined){go('editor');toast('เปิดอัลบั้มในโหมดตรวจสอบของแอดมิน')}if(e.target.dataset.tool){modal(`<h2>${e.target.closest('button').querySelector('span').childNodes[0].textContent}</h2><p>หน้าจัดการส่วนนี้พร้อมใช้งานในโหมดแอดมิน สามารถค้นหา กรอง เปลี่ยนสิทธิ์ ระงับ และดูประวัติย้อนหลังได้</p><div class="drop-zone"><b>ระบบจัดการส่วนกลาง</b><p>ข้อมูลตัวอย่างสำหรับทดสอบการทำงาน</p></div><button class="primary full" onclick="document.querySelector('#modalClose').click()">เสร็จสิ้น</button>`)}});
